# -*- coding: utf-8 -*-
"""sales_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lyidxs0B17Wl_QHjgfQJBoi959hLKRrC
"""

import pandas as pd
df = pd.read_csv("sales_data.csv")
df

print("📄 Sales Data:")
df

total_revenue = df["Total_Sales"].sum()

best_product = df.groupby("Product")["Total_Sales"].sum().idxmax()
best_product_sales = df.groupby("Product")["Total_Sales"].sum().max()

print("\nSALES ANALYSIS RESULT")
print(f"Total Revenue: ₹{total_revenue}")
print(f"Best Selling Product: {best_product}")
print(f"Revenue from Best Product: ₹{best_product_sales}")

import  matplotlib.pyplot as plt
plt.figure()
product_total_sales = df.groupby("Product")["Total_Sales"].sum()
product_total_sales.plot(kind="bar")
plt.title("Total Sales by Product")
plt.xlabel("Product")
plt.ylabel("Total Sales (₹)")
plt.tight_layout()
plt.show()

